//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC9Shortcuts31GalleryCollectionViewController : UIViewController
{
    // Error parsing type: , name: layoutMetrics
    // Error parsing type: , name: collection
    // Error parsing type: , name: delegate
    // Error parsing type: , name: contentView
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: collectionViewLayout
    // Error parsing type: , name: normalCellIdentifier
    // Error parsing type: , name: captionedCellIdentifier
    // Error parsing type: , name: previewedIndexPath
    // Error parsing type: , name: KVOController.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

