//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@interface _TtC9Shortcuts30GallerySearchSectionHeaderView : UICollectionReusableView
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: title
    // Error parsing type: , name: toggleStatus
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: toggleButton.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)didTapToggle;
- (void)contentSizeCategoryDidChange;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

