//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@interface _TtC9Shortcuts26GalleryFeaturedBannersCell : UICollectionViewCell
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: banners
    // Error parsing type: , name: horizontalInset
    // Error parsing type: , name: layoutMetrics
    // Error parsing type: , name: collectionViewLayout.storage
    // Error parsing type: , name: collectionView.storage
    // Error parsing type: , name: separatorView
    // Error parsing type: , name: longPressGestureRecognizer
}

- (CDUnknownBlockType).cxx_destruct;
- (void)handleLongPressGesture;
- (void)safeAreaInsetsDidChange;
- (void)traitCollectionDidChange:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

