//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC9Shortcuts10GlyphCache : SwiftObject
{
    // Error parsing type: , name: cache
    // Error parsing type: , name: drawingOperations
    // Error parsing type: , name: initiatedCaching
    // Error parsing type: , name: completed
    // Error parsing type: , name: size
    // Error parsing type: , name: drawingQueue
    // Error parsing type: , name: resourceAccessQueue
    // Error parsing type: , name: allCharacters
}

@end

