//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC9Shortcuts27GallerySearchViewController : UIViewController
{
    // Error parsing type: , name: layoutMetrics
    // Error parsing type: , name: previousLayoutMargins
    // Error parsing type: , name: hideAttribution
    // Error parsing type: , name: delegate
    // Error parsing type: , name: iconCache
    // Error parsing type: , name: galleryWorkflows
    // Error parsing type: , name: galleryCollections
    // Error parsing type: , name: sessionManager
    // Error parsing type: , name: lastSearchTask
    // Error parsing type: , name: previewedIndexPath
    // Error parsing type: , name: collectionView.storage
    // Error parsing type: , name: contentView.storage
    // Error parsing type: , name: searchText
    // Error parsing type: , name: reuseIdentifier
    // Error parsing type: , name: maxCollectionsToShow
    // Error parsing type: , name: showingMore
    // Error parsing type: , name: loading
    // Error parsing type: , name: reachedEnd
    // Error parsing type: , name: searchBar.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)cancel;
- (void)keyboardFrameWillChange;
- (void)updateSearchResults;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewLayoutMarginsDidChange;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

