//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol _TtP9Shortcuts29GuidedTourCoordinatorDelegate_;

@interface _TtC9Shortcuts21GuidedTourCoordinator : NSObject
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: delegate
}

- (CDUnknownBlockType).cxx_destruct;
- (id)init;
- (void)start;
- (id)initWithPresenter:(id)arg1;
@property(nonatomic) __weak id <_TtP9Shortcuts29GuidedTourCoordinatorDelegate_> delegate; // @synthesize delegate;

@end

