//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC9ShortcutsP33_6484685A68895D61F8939FA65B0A74B212InteriorView : UIView
{
    // Error parsing type: , name: style
    // Error parsing type: , name: layoutMetrics
    // Error parsing type: , name: layoutManager
    // Error parsing type: , name: glyphCharacter
    // Error parsing type: , name: glyphView
    // Error parsing type: , name: nameLabel
    // Error parsing type: , name: descriptionView
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)updateFontsWithLayoutMetrics:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

