//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC9Shortcuts25GalleryPageViewController.h"

#import "WFGalleryCollectionEditViewControllerDelegate-Protocol.h"

@interface _TtC9Shortcuts25GalleryPageViewController (Shortcuts4) <WFGalleryCollectionEditViewControllerDelegate>
- (void)collectionEditViewController:(id)arg1 didDeleteCollection:(id)arg2;
- (void)collectionEditViewController:(id)arg1 didUpdateCollection:(id)arg2;
- (void)collectionEditViewControllerDidCancel:(id)arg1;
@end

