//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@protocol _TtP9Shortcuts29ProfileViewControllerDelegate_;

@interface _TtC9Shortcuts21ProfileViewController : UIViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: user
    // Error parsing type: , name: layoutMetrics
    // Error parsing type: , name: sessionManager
    // Error parsing type: , name: workflows
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: loadingView
    // Error parsing type: , name: headerView
    // Error parsing type: , name: collectionViewWidthConstraint
    // Error parsing type: , name: animationController
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showEditProfile;
- (void)didTapDone;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithUser:(id)arg1;
@property(nonatomic) __weak id <_TtP9Shortcuts29ProfileViewControllerDelegate_> delegate; // @synthesize delegate;

@end

