//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@interface _TtC9Shortcuts25EditProfileViewController : UITableViewController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: nameRequired
    // Error parsing type: , name: user
    // Error parsing type: , name: prompt
    // Error parsing type: , name: editingUser
    // Error parsing type: , name: profilePhotoController.storage
    // Error parsing type: , name: headerView.storage
    // Error parsing type: , name: nameCell.storage
    // Error parsing type: , name: websiteCell.storage
    // Error parsing type: , name: twitterCell.storage
    // Error parsing type: , name: emailCell.storage
    // Error parsing type: , name: loadingItem.storage
    // Error parsing type: , name: saveItem.storage
    // Error parsing type: , name: identityCells.storage
    // Error parsing type: , name: newlySelectedProfilePhoto
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithStyle:(long long)arg1;
- (void)didTapProfilePhoto;
- (void)didTapSave;
- (void)didTapCancel;
- (void)tableView:(id)arg1 willDisplayFooterView:(id)arg2 forSection:(long long)arg3;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

