//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray;

@interface _TtC9Shortcuts29GalleryFeaturedViewController : UIViewController
{
    // Error parsing type: , name: pageViewController.storage
    // Error parsing type: , name: contentView.storage
    // Error parsing type: , name: viewIsVisible
    // Error parsing type: , name: queuedPageName
    // Error parsing type: , name: prewarmFetchStatus
    // Error parsing type: , name: sessionManager
    // Error parsing type: , name: searchViewController.storage
    // Error parsing type: , name: searchController.storage
    // Error parsing type: , name: hideAttribution
    // Error parsing type: , name: searchBarBackgroundHidden
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showPageWithName:(id)arg1;
- (void)present:(id)arg1;
- (void)presentWithSharedShortcut:(id)arg1;
- (void)presentLegacySearchWithQuery:(id)arg1;
- (void)beginSearchingFromKeyCommand;
- (void)didTapSearchButton;
- (void)beginSearchingWithQuery:(id)arg1;
- (void)profileButtonPressed;
- (void)refreshContent;
@property(nonatomic, readonly) NSArray *keyCommands;
- (void)viewDidDisappear:(_Bool)arg1;
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewLayoutMarginsDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

