//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC9Shortcuts21GuidedTourCoordinator.h"

@interface _TtC9Shortcuts21GuidedTourCoordinator (Shortcuts)
- (void)composeViewControllerRequestsDismissal:(id)arg1 forTutorial:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
@end

