//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface _TtC9Shortcuts25GalleryPageViewController : UIViewController
{
    // Error parsing type: , name: hideAttribution
    // Error parsing type: , name: delegate
    // Error parsing type: , name: layoutMetrics
    // Error parsing type: , name: previousLayoutMargins
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: contentOffsetsByCollectionIndex
    // Error parsing type: , name: previewedCollectionIndexPath
    // Error parsing type: , name: previewedWorkflowIndexPath
    // Error parsing type: , name: sizeCache
    // Error parsing type: , name: titleTapGestureRecognizer
    // Error parsing type: , name: page
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)presentEditViewController;
- (void)viewLayoutMarginsDidChange;
- (void)viewDidLayoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

