//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC9Shortcuts29GalleryPageEditViewController.h"

#import "_TtP9Shortcuts43GalleryFindCollectionViewControllerDelegate_-Protocol.h"

@interface _TtC9Shortcuts29GalleryPageEditViewController (Shortcuts3) <_TtP9Shortcuts43GalleryFindCollectionViewControllerDelegate_>
- (void)findCollectionViewController:(id)arg1 didFindCollection:(id)arg2;
- (void)findCollectionViewControllerDidCancel:(id)arg1;
@end

