//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@interface _TtC9Shortcuts17ProfileHeaderView : UICollectionReusableView
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: user
    // Error parsing type: , name: fullWidth
    // Error parsing type: , name: hasWebsite
    // Error parsing type: , name: showsEditButtons
    // Error parsing type: , name: profilePhotoView.storage
    // Error parsing type: , name: nameLabel
    // Error parsing type: , name: websiteView.storage
    // Error parsing type: , name: twitterView.storage
    // Error parsing type: , name: topDividerView
    // Error parsing type: , name: bottomDividerView
    // Error parsing type: , name: editProfileButton.storage
    // Error parsing type: , name: submitWorkflowButton.storage
    // Error parsing type: , name: topDividerViewLeadingConstraint.storage
    // Error parsing type: , name: topDividerViewTrailingConstraint.storage
    // Error parsing type: , name: bottomDividerViewLeadingConstraint
    // Error parsing type: , name: bottomDividerViewTrailingConstraint
    // Error parsing type: , name: websiteButtonWidthConstraint.storage
    // Error parsing type: , name: twitterViewFullWidthLeadingConstraint.storage
    // Error parsing type: , name: twitterViewNonFullWidthLeadingConstraint.storage
    // Error parsing type: , name: twitterViewNoWebsiteLeadingConstraint.storage
}

- (CDUnknownBlockType).cxx_destruct;
- (void)didTapProfileImage;
- (void)didTapSubmitWorkflow;
- (void)didTapEditProfile;
- (void)didTapTwitterButton;
- (void)didTapWebsiteButton;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

