//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError, _TtC9Shortcuts21GuidedTourCoordinator;

@protocol _TtP9Shortcuts29GuidedTourCoordinatorDelegate_
- (void)guidedTourCoordinatorWithCoordinator:(_TtC9Shortcuts21GuidedTourCoordinator *)arg1 didFinishWithError:(NSError *)arg2;
- (void)guidedTourCoordinatorDidFinishWithCoordinator:(_TtC9Shortcuts21GuidedTourCoordinator *)arg1;
@end

