//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DCThumbnailGenerator.h"

@interface DCImageThumbnailGenerator : DCThumbnailGenerator
{
}

+ (void)generateThumbnailForImage:(id)arg1 filename:(id)arg2 type:(id)arg3 size:(struct CGSize)arg4 completion:(CDUnknownBlockType)arg5;
+ (void)generateThumbnailForCGImageRef:(struct CGImage *)arg1 scale:(double)arg2 filename:(id)arg3 type:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (void)generateThumbnailForFile:(id)arg1 withSize:(struct CGSize)arg2 scale:(double)arg3 completion:(CDUnknownBlockType)arg4;
+ (id)supportedTypes;
+ (void)load;

@end

