//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class INRunWorkflowIntent;

@protocol INRunWorkflowIntentHandling <NSObject>
- (void)handleRunWorkflow:(INRunWorkflowIntent *)arg1 completion:(void (^)(INRunWorkflowIntentResponse *))arg2;

@optional
- (void)resolveWorkflowForRunWorkflow:(INRunWorkflowIntent *)arg1 withCompletion:(void (^)(INRunWorkflowWorkflowResolutionResult *))arg2;
- (void)confirmRunWorkflow:(INRunWorkflowIntent *)arg1 completion:(void (^)(INRunWorkflowIntentResponse *))arg2;
@end

