//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_source;

@interface WFDispatchSourceTimer : NSObject
{
    double _interval;
    NSObject<OS_dispatch_source> *_source;
}

+ (id)scheduledTimerWithInterval:(double)arg1 handler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSObject<OS_dispatch_source> *source; // @synthesize source=_source;
@property(readonly, nonatomic) double interval; // @synthesize interval=_interval;
- (void).cxx_destruct;
- (void)cancel;
- (void)start;
- (void)dealloc;
- (id)initWithInterval:(double)arg1 queue:(id)arg2 handler:(CDUnknownBlockType)arg3;

@end

