//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UIDocumentMenuDelegate-Protocol.h"
#import "UIDocumentPickerDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, UIViewController, WFFileType;

@interface WFGalleryAssetPicker : NSObject <UIDocumentMenuDelegate, UIDocumentPickerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    WFGalleryAssetPicker *_strongSelf;
    CDUnknownBlockType _completionHandler;
    NSString *_assetDescription;
    WFFileType *_assetType;
    UIViewController *_viewController;
    struct CGSize _assetSize;
}

@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) WFFileType *assetType; // @synthesize assetType=_assetType;
@property(nonatomic) struct CGSize assetSize; // @synthesize assetSize=_assetSize;
@property(copy, nonatomic) NSString *assetDescription; // @synthesize assetDescription=_assetDescription;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
- (void)documentPickerWasCancelled:(id)arg1;
- (void)documentPicker:(id)arg1 didPickDocumentAtURL:(id)arg2;
- (void)documentMenuWasCancelled:(id)arg1;
- (void)documentMenu:(id)arg1 didPickDocumentPicker:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)autoreleaseSelf;
- (void)retainSelf;
- (void)confirmImageSize:(id)arg1 withViewController:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)finishWithImage:(id)arg1 file:(id)arg2 error:(id)arg3;
- (void)finishWithError:(id)arg1;
- (void)presentFromViewController:(id)arg1 sourceView:(id)arg2 sourceRect:(struct CGRect)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

