//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WorkflowUI/WFEditWorkflowViewController.h>

@interface WFGuidedWorkflowViewController : WFEditWorkflowViewController
{
    _Bool _inserted;
    _Bool _showsPlaceholder;
}

+ (_Bool)displaysEmptyView;
@property(nonatomic) _Bool showsPlaceholder; // @synthesize showsPlaceholder=_showsPlaceholder;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForFooterInSection:(long long)arg3;
- (void)workflow:(id)arg1 removeAction:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)canMoveActionsAtIndexes:(id)arg1 toIndexes:(id)arg2;
- (id)initialIndexPathForDragController:(id)arg1;
- (_Bool)actionShouldHideConfiguration:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithWorkflow:(id)arg1 context:(id)arg2;

@end

