//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WFHandoffCompletionNotifier : NSObject
{
}

+ (void)addHandoffObserver:(id)arg1 forActivityType:(id)arg2;
+ (void)completedHandoffWithActivityType:(id)arg1 handoffSource:(id)arg2;

@end

