//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WorkflowUI/WFEditableLibraryResultsController.h>

@class NSIndexPath;

@interface WFHomeResultsController : WFEditableLibraryResultsController
{
}

- (_Bool)collectionView:(id)arg1 canMoveItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(readonly, nonatomic) NSIndexPath *createWorkflowIndexPath;
- (void)setCellLayoutMetrics:(id)arg1;
- (_Bool)shouldScrollToInsertionAtIndexPath:(id)arg1;
- (_Bool)shouldShowCreateWorkflowCellInSection:(long long)arg1;
- (void)setSearching:(_Bool)arg1;
- (id)initWithWorkflows:(id)arg1 collectionView:(id)arg2 runCoordinator:(id)arg3;
- (id)initWithCollections:(id)arg1 forSections:(id)arg2 block:(CDUnknownBlockType)arg3;

@end

