//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class INInteraction, NSString;

@interface WFIntentExtensionConfirmationMessage : NSObject <NSSecureCoding>
{
    INInteraction *_interaction;
    NSString *_workflowID;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSString *workflowID; // @synthesize workflowID=_workflowID;
@property(copy, nonatomic) INInteraction *interaction; // @synthesize interaction=_interaction;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithWorkflowID:(id)arg1 interaction:(id)arg2;

@end

