//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, WFLibraryRunCoordinator, WFWorkflow;

@protocol WFLibraryRunCoordinatorObserver <NSObject>

@optional
- (void)runCoordinator:(WFLibraryRunCoordinator *)arg1 didFinishRunningWorkflow:(WFWorkflow *)arg2 withError:(NSError *)arg3;
- (void)runCoordinator:(WFLibraryRunCoordinator *)arg1 didChangeRunningStateWithProgress:(double)arg2 forWorkflow:(WFWorkflow *)arg3;
@end

