//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface WFMessagePortActionRunnerServer : NSObject
{
    struct __CFMessagePort *_port;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) struct __CFMessagePort *port; // @synthesize port=_port;
- (void).cxx_destruct;
- (id)handleMessageWithID:(int)arg1 data:(id)arg2;
- (void)dealloc;
- (id)initWithServiceName:(id)arg1;

@end

