//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WFWatchConnectivityMessageHandler-Protocol.h"

@interface WFRemoteContentItemCoercer : NSObject <WFWatchConnectivityMessageHandler>
{
}

+ (void)handleMessage:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
+ (void)coerceItem:(id)arg1 toItemClasses:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)getFileRepresentations:(CDUnknownBlockType)arg1 forType:(id)arg2 fromItem:(id)arg3;
+ (void)getObjectRepresentations:(CDUnknownBlockType)arg1 forClass:(Class)arg2 fromItem:(id)arg3;
+ (void)load;

@end

