//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WFWatchConnectivityMessageHandler-Protocol.h"

@interface WFRemoteActionRunner : NSObject <WFWatchConnectivityMessageHandler>
{
}

+ (void)cancelCurrentlyRunningAction;
+ (void)runActionWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)_cancelCurrentlyRunningAction;
+ (void)_runActionWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)handleMessage:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
+ (void)load;

@end

