//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WFWatchConnectivityMessageHandler-Protocol.h"

@interface WFRemoteQuickLookFetcher : NSObject <WFWatchConnectivityMessageHandler>
{
}

+ (void)locallyGetQuickLookDetailsForFileItem:(id)arg1 thumbnailSize:(struct CGSize)arg2 thumbnailScale:(double)arg3 completionHandler:(CDUnknownBlockType)arg4;
+ (void)fetchQuickLookDetailsForMediaItem:(id)arg1 artworkSize:(struct CGSize)arg2 artworkScale:(double)arg3 completionHandler:(CDUnknownBlockType)arg4;
+ (void)handleMessage:(id)arg1 replyHandler:(CDUnknownBlockType)arg2;
+ (void)load;

@end

