//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray;
@protocol WFTermsAndConditionsViewControllerDelegate;

@interface WFTermsAndConditionsViewController : UITableViewController
{
    id <WFTermsAndConditionsViewControllerDelegate> _delegate;
    NSArray *_paragraphs;
}

@property(copy, nonatomic) NSArray *paragraphs; // @synthesize paragraphs=_paragraphs;
@property(nonatomic) __weak id <WFTermsAndConditionsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)donePressed;
- (void)loadView;
- (id)initWithStyle:(long long)arg1;

@end

