//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIView;

@interface WFTodayCustomizeButton : UIButton
{
    UIView *_dimmingView;
    struct UIEdgeInsets _separatorInset;
}

@property(nonatomic) __weak UIView *dimmingView; // @synthesize dimmingView=_dimmingView;
@property(nonatomic) struct UIEdgeInsets separatorInset; // @synthesize separatorInset=_separatorInset;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)init;

@end

