//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class UILabel, UIView, WFTodayCustomizeButton;

@interface WFTodayFooterView : UICollectionReusableView
{
    WFTodayCustomizeButton *_customizeButton;
    UILabel *_customizeLabel;
    UIView *_separatorView;
    struct UIEdgeInsets _separatorInset;
}

+ (id)defaultReuseIdentifier;
@property(nonatomic) __weak UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(nonatomic) __weak UILabel *customizeLabel; // @synthesize customizeLabel=_customizeLabel;
@property(nonatomic) __weak WFTodayCustomizeButton *customizeButton; // @synthesize customizeButton=_customizeButton;
@property(nonatomic) struct UIEdgeInsets separatorInset; // @synthesize separatorInset=_separatorInset;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

