//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FICImageCache, NSString;

@interface WFTodayLabelImageProvider : NSObject
{
    NSString *_currentImageFormatName;
    FICImageCache *_imageCache;
    struct CGSize _sizeAvailableForLabel;
}

+ (id)sharedProvider;
@property(nonatomic) struct CGSize sizeAvailableForLabel; // @synthesize sizeAvailableForLabel=_sizeAvailableForLabel;
- (void).cxx_destruct;
- (id)imageFormatNameForSize:(struct CGSize)arg1;
- (void)getLabelImageForWorkflow:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setupCacheForCurrentSize;
- (void)dealloc;
- (id)init;

@end

