//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSUserDefaults;

@interface WFTutorialProgressStore : NSObject
{
    _Bool _tutorialCompleted;
    _Bool _tutorialCompletedExternally;
    _Bool _checkedExternalTutorialCompletion;
    NSUserDefaults *_userDefaults;
}

@property(nonatomic) _Bool checkedExternalTutorialCompletion; // @synthesize checkedExternalTutorialCompletion=_checkedExternalTutorialCompletion;
@property(retain, nonatomic) NSUserDefaults *userDefaults; // @synthesize userDefaults=_userDefaults;
- (void).cxx_destruct;
@property(nonatomic) _Bool hasSeenWelcomeScreen;
- (void)ubiquitousKVSDidChange:(id)arg1;
- (void)setTutorialCompleted:(_Bool)arg1 includingUbiquitiousStore:(_Bool)arg2;
@property(nonatomic) _Bool tutorialCompleted; // @synthesize tutorialCompleted=_tutorialCompleted;
- (void)externalTutorialCompletionStatusUpdated:(_Bool)arg1;
- (void)setTutorialCompletedExternally:(_Bool)arg1 synchronizeImmediately:(_Bool)arg2;
@property(readonly, nonatomic) _Bool tutorialCompletedExternally; // @synthesize tutorialCompletedExternally=_tutorialCompletedExternally;
- (void)dealloc;
- (id)initWithUserDefaults:(id)arg1;

@end

